### ISSUE TITLE
회원가입시 존재하는 회원일때 계속해서 로딩 컴포넌트가 표시되는 현상

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-web#120]
## 상세 설명

회원가입시 존재하는 회원일때 요청이 완료되었을때도 계속해서 로딩 컴포넌트가 표시되는 현상이 있습니다.

## 스크린샷

![image](https://user-images.githubusercontent.com/63437430/149720572-953f364f-61c2-47ee-8531-c0a72ba82e5d.png)

**Comment by choi2021** [comment]
https://github.com/GIST-Petition-Site-Project/GIST-petition-web-ts/pull/172
