### ISSUE TITLE
반응형 추가

### ISSUE THREAD

**Issue by choi2021** [GIST-Petition-Site-Project/GIST-petition-web#122]
## 목적

모바일과 같은 다양한 크기의 매체에 맞게 반응형으로 만드려고 합니다.

## 작업 목록

- [x] 스크린 크기 기준 정하기
- [x] 스크린 크기별 style 최적화

**Comment by gpgun0** [comment]
기획부터 같이 해봅시다!

**Comment by gpgun0** [comment]
반응형 이슈는 해결 됐다고 생각하기 때문에 이슈 닫도록 하겠습니다.
