### ISSUE TITLE
회원가입 부분 수정 

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-web#124]
## 목적

이메일을 잘못된 형식으로 입력한 후 다시 제대로 입력하여 인증코드 요청을 보내면 에러메세지가 그대로 노출됩니다.

또한 로딩관련해서도 로직을 다듬으면 좋을것 같습니다.

**Comment by choi2021** [comment]
https://github.com/GIST-Petition-Site-Project/GIST-petition-web-ts/pull/172
