### ISSUE TITLE
회원 가입 약관 페이지 제작합니다.

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#125]
## 목적
회원 가입 약관 페이지 제작합니다.

타 사이트를 참고하고 동의가 필요한 항목들을 제작합니다.

## 작업 목록

- [ ]

**Comment by choi2021** [comment]
https://github.com/GIST-Petition-Site-Project/GIST-petition-web-ts/pull/172
