### ISSUE TITLE
로그인/로그아웃 전환 UX가 부자연스러운 것 같습니다

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#129]
## 목적
로그인/로그아웃 전환 UX가 부자연스러운 것 같습니다

로그아웃 누르면 바로 로그인으로 바뀌니 어색한 것 같습니다.
모달창을 띄워주면 될 것 같은데 다른 아이디어 있으면 남겨주세요!

**Comment by kimjngyun** [comment]
토스트로 전환을 알려주는 작업을 제가 진행하도록 하겠습니다.
