### ISSUE TITLE
페이지마다 footer component 추가

### ISSUE THREAD

**Issue by choi2021** [GIST-Petition-Site-Project/GIST-petition-web#144]
## 목적
만든 footer를 페이지들에 추가하려합니다.

## 작업 목록

- 페이지마다 css스타일로 위치 조정
- 반응형에 맞게 조정

![image](https://user-images.githubusercontent.com/80830981/153639269-f5e4a053-2673-4a78-89bc-a38d405d01a3.png)

**Comment by kimjngyun** [comment]
Footer 는 App.tsx에서 RootRouter 컴포넌트 밑에 넣어주면 될거같아요. 
혹시 페이지 마다 따로 작업하는 이유가 있을까요?

**Comment by choi2021** [comment]
저번 회의때 얘기했던 login 페이지에 경우에 footer가 가장 아래가 아니라 올라올 것 같아서 페이지 마다라고 생각을 했었습니다. 우선 app.tsx에서 한번에 넣어보고 괜찮으면 그대로 사용하고 아니면 따로 조정해보겠습니다.

**Comment by kimjngyun** [comment]
넵! 감사합니다~
