### ISSUE TITLE
 Petition리스트에 Tag 추가

### ISSUE THREAD

**Issue by leejimin-gist** [GIST-Petition-Site-Project/GIST-petition-web#167]
## 목적
사전동의여부, 청원진행 여부를 나타내는 tag 필요

## 작업 목록

- [ ] Tag 추가
- [ ] 반응형 반영

**Comment by gpgun0** [comment]
일단 나의 청원에서만 태그를 넣을 수 있나요?

모든 청원은 어차피 사전 동의 받았고 청원 진행중인 글들만 보여주기 때문에요

**Comment by leejimin-gist** [comment]
> 일단 나의 청원에서만 태그를 넣을 수 있나요?
> 
> 모든 청원은 어차피 사전 동의 받았고 청원 진행중인 글들만 보여주기 때문에요

그러면 Petition List와 myPetition List를 분리하겠습니다.
