### ISSUE TITLE
회원가입,로그인, 비밀번호 찾기 스타일링 통일

### ISSUE THREAD

**Issue by choi2021** [GIST-Petition-Site-Project/GIST-petition-web#248]
## 목적

회원가입 페이지의 스타일링이 로그인과 비밀번호 찾기와 다르게 적용되어 있습니다.
통일해주려합니다.

## 작업 목록

- [ ] login 스타일링 참고해서 수정하기

**Comment by gpgun0** [comment]
회원가입 페이지 지금 반영할게요
