### ISSUE TITLE
회원 약관 에러 메세지가 다음 페이지에도 계속 뜨는 현상이 발생합니다.

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#271]
## 상세 설명

회원 약관 에러 메세지가 계속 뜨는 현상이 발생합니다. 

## 스크린샷

![스크린샷 2022-02-28 오후 12 25 00](https://user-images.githubusercontent.com/65757344/155918925-cd362eb9-2401-49d3-9492-33d2997f6f89.png)

## 대처 방안

로직을 수정하거나
아니면 CapsLock 메세지처럼  
일정 시간동안만 띄우는 방법도 있습니다.

**Comment by choi2021** [comment]
오늘 맡아서 수정해보겠습니다.
