### ISSUE TITLE
답변 완료된 청원에 대해 공유와 동의 가능하게 합니다.

### ISSUE THREAD

**Issue by leejimin-gist** [GIST-Petition-Site-Project/GIST-petition-web#277]
## 목적
답변 완료된 청원을 공유를 가능하게 하는 건 어떨지?
(동의를 하는 것 이전에, 청원의 내용을 공유하는 것이 목표는 아닐까?)
답변이 완료되더라도 동의를 계속할 수 있게 하는 건 어떨지?
(50명이 동의를 하고 빠르게 답변해버리면, 여러 사람의 의견이 반영되지 않은 것으로 보일수도 있을듯)

## 작업 목록

- [ ] A
- [ ] B

**Comment by gpgun0** [comment]
해당 이슈는 최근 날린 pr에서 해결해놓았습니다.
