### ISSUE TITLE
AuthRoute로 감싸진 Route만 로그인 성공후 redirection로직이 적용됩니다.

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#294]
## 상세 설명

AuthRoute로 감싸진 Route만 hash를 이용한 로그인 성공시 redirection로직이 적용됩니다.

## 스크린샷

예시. write 페이지
<img width="653" alt="스크린샷 2022-03-12 오전 1 34 36" src="https://user-images.githubusercontent.com/65757344/157908842-0c65150e-f8b7-4900-a25d-2ad42f09455e.png">

## 대처 방안

대처 방안을 알고 있다면 작성해주세요.

**Comment by kimjngyun** [comment]
제가 해결해놓을게요
