### ISSUE TITLE
네비게이션 바 좌우 패딩 추가 제안

### ISSUE THREAD

**Issue by kimjngyun** [GIST-Petition-Site-Project/GIST-petition-web#56]
## 목적

폭이 좁아졌을때 딱 붙기보단 좌우에 패딩이 있으면 합니다.

## 작업 목록

- [ ] NavBar에 좌우 패딩을 추가합니다.

## 참고 사항

![image](https://user-images.githubusercontent.com/63437430/148977695-e2ddf845-6397-471b-afdc-6a4da044214c.png)

**Comment by leejimin-gist** [comment]
좋은 제안 같습니다

**Comment by choi2021** [comment]
지민님 navbar 반응형 수정 commit으로 수정되어 issue 닫겠습니다.
