### ISSUE TITLE
청원 작성 API 연결합니다.

### ISSUE THREAD

**Issue by gpgun0** [GIST-Petition-Site-Project/GIST-petition-web#65]
## 목적

청원 작성 API 연결합니다.

## 작업 목록

- [x] PostEditor, PrecautionModal, WritePrecaution 컴포넌트들을 Write 페이지 안에 정리한다
- [x] 제목 글자 수는 10자 이상으로 제한을 둔다
- [x] 카테고리 입력은 필수다
- [x] 위 조건이 모두 만족되면 작성 버튼이 활성화 된다
- [ ] 작성 버튼을 누르면 삭제 불가 주의사항 모달창을 띄운다
- [x] 청원 작성이 성공하면 작성한 페이지로 이동한다
- [ ] 위 작업이 어려우면 모든 청원 페이지로 이동한다
- [x] 작성 취소를 하면 뒤로 이동한다
- [ ] 위 사항을 테스트한다

**Comment by kimjngyun** [comment]
작성 버튼을 누르면 삭제 불가 주의사항 모달창을 띄운다
 위 작업이 어려우면 모든 청원 페이지로 이동한다
=> 이 부분은 청원 게시글 목록 (/posts) 로 가면 좋겠습니다.
