### ISSUE TITLE
CSS 속성 값 정리 제안

### ISSUE THREAD

**Issue by choi2021** [GIST-Petition-Site-Project/GIST-petition-web#89]
## 목적
ts file에  반복적으로 사용되는 값들을 common folder에 넣어서 색깔이나 공통된 크기들을 변수로 정리하려합니다.
고정된 값인 px에서 rem과 em으로 바꾸어주려합니다.

## 작업 목록

- [ ] css file들을 변수로 받아올 수 있게 통합 css file생성, 정리
- [ ] 고정된 px에서 rem과 em으로 변환

## 참고 사항
post css를 사용해서 수정해보려했지만 post css는 css style 전체를 바꿀것 같아서 
styled component 방법내에서 적용법을 공부해서 적용하겠습니다.

**Comment by gpgun0** [comment]
Good!

px값 변경할 때 반응형 신경쓰면서 수정 부탁드립니다
